### ISSUE TITLE
Plugin doesn't start without udev rules for USB adaptor DS1420

### ISSUE THREAD

**Issue by jaywax** [vdomos/domogik-plugin-onewired#14]
Have to put this on udevrules under debian jessie (domogik 0.5.2) :
`SUBSYSTEMS=="usb", ATTRS{idVendor}=="04fa", ATTRS{idProduct}=="2490", SYMLINK+="onewire", MODE="0666` 

Here's the log for the plugin :
`2017-05-29 14:00:26,617 domogik-onewired INFO Value for '1-wire_cache' is : N
2017-05-29 14:00:26,617 domogik-onewired INFO Casting value for key '1-wire_cache' in type 'boolean'...
2017-05-29 14:00:26,618 domogik-onewired INFO Value is : False
2017-05-29 14:00:26,618 domogik-onewired INFO Retrieve the devices list for this client...
2017-05-29 14:00:26,675 domogik-onewired INFO - id : 55  /  name : baie serveurs  /  device type id : onewire.thermometer_temp
2017-05-29 14:00:26,675 domogik-onewired INFO   xpl_stats features :
2017-05-29 14:00:26,676 domogik-onewired INFO   xpl_commands features :
2017-05-29 14:00:26,677 domogik-onewired INFO ==> OWFS version : 2.9p8
2017-05-29 14:00:26,841 domogik-onewired ERROR ### Access to onewire device is not possible:  Traceback (most recent call last):
  File "/var/lib/domogik/domogik_packages/plugin_onewired/lib/onewired.py", line 69, in __init__
    ow.init(dev)
  File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 224, in init
    raise exNoController
exNoController

2017-05-29 14:00:26,842 domogik-onewired DEBUG force_leave called
2017-05-29 14:00:26,842 domogik-onewired DEBUG Send client status : stopped
2017-05-29 14:00:26,846 domogik-onewired INFO The thread send_status_loop was not registered, killing it
2017-05-29 14:00:26,888 domogik-onewired INFO Thread send_status_loop stopped.
2017-05-29 14:00:26,889 domogik-onewired INFO The thread send_process_info was not registered, killing it
2017-05-29 14:00:26,889 domogik-onewired INFO Thread send_process_info stopped.
2017-05-29 14:00:26,953 domogik-onewired DEBUG Delete the file /var/run/domogik//onewired_return_code_1273
2017-05-29 14:00:26,953 domogik-onewired DEBUG __del__ Single client
2017-05-29 14:00:26,954 domogik-onewired DEBUG force_leave called
`

**Comment by jaywax** [comment]
Due to personnal error configuration. Udev must not need to be used if owserver is used...
