### ISSUE TITLE
code 500

### ISSUE THREAD

**Issue by tikismoke** [vdomos/domogik-plugin-onewired#8]
In advanced page in no error in log i got a code 500 from the admin.

**Comment by vdomos** [comment]
Can you kill admin and restart with '-f' to see error message when acces to
the advanced page ?

thanks

2016-06-01 17:36 GMT+02:00 tikismoke notifications@github.com:

**Comment by tikismoke** [comment]
Yes got it :)

```

uests': '1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/domogik/domogik_packages/plugin_onewired/admin/__init__.py", line 70, in index
    informations = get_informations(device),
  File "/var/lib/domogik/domogik_packages/plugin_onewired/admin/__init__.py", line 33, in get_informations
    for device in ow.Sensor("/").find(all = True):    #.find(type = "DS18B20"):
  File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 271, in __init__
    self.useCache( self._useCache )
  File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 417, in useCache
    for n in owfs_get( self._usePath ).split( ',' ) ] )
  File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 159, in _get
    raise exUnknownSensor(path)
exUnknownSensor: '/'


```

Sorry was difficult to catch

**Comment by tikismoke** [comment]
I can reproduce it.
Stop the plugin
Start it=>got to advanced=>Very lots of refresh page (F5)=>code 500.

Or wait a day or two

**Comment by tikismoke** [comment]
It do not solve the real problem but cath the exception and display an error message instead of device list like this:
https://snag.gy/Uxhl4u.jpg
